apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  namespace: test-ns
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebcontainer
    image: examplesdocker/javawebapp:1
    ports:
      - containerPort: 8080
